name: simpy
channels:
  - defaults
dependencies:
  - joblib=1.1
  - jupyter=1.0
  - jupyterlab=3.5
  - matplotlib=3.6
  - numpy=1.23
  - pandas=1.5
  - pip=22.3
  - pytest=7.1
  - python=3.10  
  - scipy=1.9
  - pip:
    - simpy==4.0

